### ISSUE TITLE
Support for bash auto completion

### ISSUE THREAD

**Issue by surajssd** [dustymabe/fedpkg-kompose#4]
kompose supports bash auto completion, should this package do something about it?

ping @dustymabe

**Comment by dustymabe** [comment]
suggestions?

**Comment by surajssd** [comment]
i don't know how that can be done by rpm, it can be done manually by users so can that be automated and user does not have to do it?

```
source <(kompose completion bash)
```

doc: https://github.com/kubernetes-incubator/kompose#shell-autocompletion

**Comment by dustymabe** [comment]
i think we would need to create a file that is delivered by the rpm and persists. One example is `/usr/share/bash-completion/completions/dnf`. So we could just create `/usr/share/bash-completion/completions/kompose` when we build the rpm and that can be delivered by the rpm.

**Comment by dustymabe** [comment]
fixed in #5
